[package]
name = "shalf-core"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
serde = { version = "1.0.218", features = ["derive"] }
toml = { version = "0.8.20", features = ["parse"] }
